#!/usr/bin/env python
# -*- coding: utf-8 -*-

import subprocess
from hashlib import md5
from getpass import getpass

GARBAGE = "bilik!PATUH7lamur3Kelek%kabarKLAIM%!papakPaser5173&#"


class _GiveMeAKey(object):

    def __init__(self, uri, user, secret):
        if uri:
            self.uri = uri
        else:
            self.uri = ""
        if user:
            self.user = user
        else:
            self.user = ""
        if secret:
            self.secret = secret
        else:
            self.secret = ""
        self.wordset = [
            'abadi', 'abang', 'abjad', 'abrik', 'absah', 'absen', 'abses',
            'acara', 'acuan', 'adres', 'aduan', 'afair', 'afdal', 'afiat',
            'agama', 'agung', 'ajaib', 'ajang', 'ajuan', 'akbar', 'akhir',
            'akrab', 'aksen', 'akses', 'aktif', 'aktor', 'alami', 'alang',
            'alarm', 'alias', 'alibi', 'allah', 'alwah', 'ambah', 'ambai',
            'ambal', 'amben', 'ambet', 'ambil', 'ampai', 'ampas', 'ampuh',
            'ampun', 'ancar', 'ancol', 'andai', 'andal', 'andan', 'andil',
            'aneka', 'angan', 'angin', 'angka', 'anglo', 'angon', 'animo',
            'anjur', 'antek', 'antik', 'antre', 'anyam', 'anyep', 'anyih',
            'anyir', 'apkir', 'apung', 'arang', 'arena', 'aroma', 'artis',
            'arwah', 'asasi', 'asbut', 'asese', 'asgar', 'asing', 'aspal',
            'aspek', 'asyik', 'ateis', 'atlas', 'atlet', 'aulia', 'aurat',
            'aurum', 'awang', 'babad', 'babak', 'babat', 'babon', 'babut',
            'bacin', 'bacok', 'bacot', 'badai', 'badak', 'badal', 'badan',
            'badut', 'bagai', 'bagak', 'bagan', 'bagas', 'bagus', 'bahak',
            'baham', 'bahan', 'bahas', 'bajak', 'bajul', 'bakal', 'bakat',
            'bakir', 'bakti', 'bakul', 'balah', 'balai', 'balak', 'balam',
            'balas', 'balau', 'balig', 'balik', 'balok', 'balon', 'balun',
            'balur', 'balut', 'bambu', 'banci', 'bando', 'bantu', 'bapak',
            'barak', 'baran', 'baret', 'baris', 'baruh', 'barut', 'basah',
            'basau', 'basil', 'basis', 'basuh', 'batal', 'batas', 'batih',
            'batik', 'batil', 'batin', 'batok', 'batuk', 'bawah', 'bawel',
            'bayan', 'bayar', 'bazar', 'bebal', 'beban', 'bebas', 'bebat',
            'bebek', 'beber', 'becak', 'becek', 'becus', 'bedah', 'bedak',
            'bedel', 'bedil', 'bedol', 'beduk', 'begah', 'begal', 'bejat',
            'bekal', 'bekas', 'beken', 'beker', 'bekuk', 'belah', 'belai',
            'belam', 'belas', 'belat', 'belau', 'belek', 'belia', 'belit',
            'belok', 'beluk', 'belur', 'belus', 'benak', 'benar', 'benci',
            'benda', 'bendi', 'bendo', 'benih', 'benua', 'berai', 'berak',
            'beras', 'berat', 'beres', 'berim', 'berok', 'besar', 'beset',
            'besok', 'betah', 'betak', 'betik', 'beton', 'betul', 'biadi',
            'biang', 'biara', 'biasa', 'biaya', 'bibel', 'bibir', 'bibit',
            'bidah', 'bidak', 'bidal', 'bidan', 'bijak', 'bijan', 'bijih',
            'biksu', 'bilal', 'bilas', 'bilik', 'bilur', 'binal', 'binar',
            'birai', 'birit', 'bisai', 'bisik', 'bisul', 'bivak', 'blong',
            'bobol', 'bobot', 'bocah', 'bocor', 'bodoh', 'bogel', 'bogor',
            'bokca', 'boleh', 'bomoh', 'bonus', 'borok', 'boros', 'bosan',
            'botak', 'botor', 'brata', 'buana', 'buang', 'buaya', 'bubar',
            'bubuk', 'bubut', 'budak', 'budek', 'buduk', 'bufet', 'bugar',
            'bugil', 'buhuk', 'buhul', 'bujal', 'bujuk', 'bujur', 'bukan',
            'bukit', 'bukti', 'bulai', 'bulan', 'bulat', 'buluh', 'bulus',
            'bumbu', 'bunda', 'bunga', 'buntu', 'bunuh', 'bunyi', 'buram',
            'buras', 'burik', 'burit', 'buron', 'bursa', 'buruh', 'buruk',
            'burut', 'busat', 'busuk', 'busur', 'busut', 'butek', 'butir',
            'butuh', 'butut', 'buyar', 'buyut', 'cabai', 'cabik', 'cabir',
            'cabuk', 'cabul', 'cacah', 'cacak', 'cacar', 'cacat', 'cadar',
            'cadas', 'cadel', 'cadik', 'cagak', 'cagar', 'caguh', 'cahar',
            'caing', 'cakak', 'cakap', 'cakar', 'calak', 'calar', 'calit',
            'calon', 'caluk', 'camar', 'camca', 'canai', 'canda', 'candu',
            'cante', 'capah', 'capak', 'capek', 'capik', 'capit', 'capuk',
            'carik', 'carut', 'catak', 'catat', 'catur', 'catut', 'caung',
            'cawan', 'cawat', 'cawis', 'cebol', 'cebur', 'cedok', 'cegak',
            'cegar', 'cekah', 'cekak', 'cekal', 'cekel', 'ceker', 'celah',
            'celak', 'celek', 'celih', 'celik', 'celum', 'celus', 'cemar',
            'cemas', 'cemeh', 'cemek', 'cemer', 'cempe', 'cepak', 'cepat',
            'ceper', 'cepol', 'cerah', 'cerai', 'cerap', 'cerat', 'cerca',
            'cerek', 'ceria', 'cerna', 'ceruk', 'cetak', 'cetek', 'cewek',
            'cicik', 'ciduk', 'cigak', 'cikal', 'cikar', 'cikun', 'cilap',
            'cilik', 'cinta', 'cipta', 'cirit', 'citra', 'coang', 'cobek',
            'cocok', 'cocor', 'codet', 'cogah', 'cokar', 'coket', 'colek',
            'comar', 'comel', 'copet', 'copot', 'corak', 'coret', 'corot',
            'cotok', 'cuaca', 'cucuk', 'cucur', 'cukai', 'cukil', 'cukit',
            'cukup', 'cukur', 'culas', 'culim', 'cumbu', 'cunam', 'cupet',
            'cupul', 'curai', 'curam', 'curat', 'dacin', 'dadah', 'dahak',
            'dahan', 'dajal', 'dakar', 'dakon', 'dakwa', 'dalam', 'dalih',
            'dalil', 'damai', 'damar', 'damba', 'damik', 'danau', 'dansa',
            'danuh', 'dapat', 'dapur', 'darah', 'darat', 'darma', 'dasar',
            'datar', 'datuk', 'dawai', 'dawat', 'debar', 'debat', 'debil',
            'debit', 'dedak', 'dedal', 'dedel', 'dedes', 'degam', 'degan',
            'degap', 'degil', 'degub', 'dekak', 'dekap', 'dekat', 'dekik',
            'dekil', 'dekor', 'delan', 'delik', 'delta', 'demam', 'demek',
            'demen', 'denah', 'denai', 'denda', 'depak', 'depan', 'depot',
            'derai', 'deram', 'deras', 'derek', 'deret', 'derma', 'desah',
            'desir', 'desis', 'desus', 'detak', 'detik', 'dewan', 'diare',
            'didik', 'dikit', 'dikte', 'dinas', 'dipan', 'doang', 'dobel',
            'dodol', 'dogma', 'dokar', 'domba', 'donor', 'dosen', 'dosis',
            'doyan', 'drama', 'duafa', 'duaja', 'duane', 'dubur', 'duduk',
            'dugal', 'duhai', 'dukuh', 'dukun', 'dungu', 'dunia', 'duren',
            'durja', 'dusta', 'dusun', 'duyun', 'eceng', 'edisi', 'egois',
            'ejaan', 'eksak', 'ekses', 'elang', 'elips', 'elite', 'embah',
            'embak', 'ember', 'embun', 'emosi', 'empat', 'emper', 'empuk',
            'encer', 'encok', 'endap', 'engah', 'engku', 'entah', 'entri',
            'enyah', 'erang', 'ercis', 'erosi', 'eskan', 'etape', 'etnis',
            'faali', 'fabel', 'fajar', 'fakir', 'faksi', 'fakta', 'fardu',
            'farik', 'fasad', 'fasia', 'fasid', 'fasih', 'fasik', 'fatah',
            'fatal', 'fatwa', 'fauna', 'feses', 'fiber', 'figur', 'fiksi',
            'final', 'finis', 'firma', 'fisik', 'fitur', 'flora', 'fokus',
            'fonem', 'forte', 'forum', 'front', 'futur', 'gabah', 'gabus',
            'gadai', 'gadis', 'gaduh', 'gagah', 'gagak', 'gagal', 'gagap',
            'gajah', 'gajih', 'gajus', 'galah', 'galak', 'galas', 'galat',
            'galau', 'galur', 'gamal', 'gamam', 'gamet', 'gamis', 'gamit',
            'ganas', 'ganda', 'ganti', 'gapai', 'garai', 'garam', 'garba',
            'garda', 'gardu', 'garis', 'garit', 'garpu', 'garuk', 'garut',
            'gasal', 'gatal', 'gatra', 'gaung', 'gawai', 'gawat', 'gawir',
            'gedek', 'gegar', 'gegep', 'geger', 'gelap', 'gelar', 'gelas',
            'gemar', 'gemas', 'gempa', 'gemuk', 'genap', 'genit', 'genre',
            'genta', 'genus', 'gerah', 'gerai', 'gerak', 'geram', 'gerek',
            'geret', 'gerik', 'germo', 'gerus', 'gesit', 'getah', 'getar',
            'getas', 'getek', 'getir', 'getok', 'gigih', 'gigit', 'gilap',
            'gilir', 'gincu', 'girik', 'gitar', 'globe', 'gocek', 'godam',
            'godek', 'godot', 'gohok', 'golok', 'gopoh', 'gores', 'gosip',
            'gosok', 'gowok', 'goyah', 'grasi', 'griya', 'grogi', 'gubal',
            'gubuk', 'gugup', 'gugur', 'gugus', 'gulam', 'gumam', 'gumpa',
            'gumuk', 'gundu', 'gurat', 'gurau', 'gurdi', 'gurih', 'guruh',
            'gurun', 'gusar', 'gusti', 'guyon', 'guyub', 'habib', 'habis',
            'hadap', 'hadir', 'hadis', 'hafal', 'hajar', 'hajat', 'hakim',
            'halte', 'halus', 'hamba', 'hamil', 'hampa', 'hantu', 'hanya',
            'hapus', 'haram', 'harap', 'harga', 'harta', 'harum', 'harus',
            'hasil', 'hasta', 'hayat', 'hebat', 'heboh', 'helai', 'hemat',
            'henti', 'heran', 'hewan', 'hibah', 'hidup', 'hijau', 'hilal',
            'hilir', 'himen', 'himne', 'hirau', 'hiruk', 'hisab', 'hitam',
            'horor', 'hotel', 'hujan', 'hujat', 'hukum', 'humor', 'humus',
            'hunus', 'huruf', 'hutan', 'ialah', 'iblis', 'ideal', 'idiom',
            'idiot', 'idola', 'ihram', 'ihwal', 'ijmal', 'iklan', 'iklim',
            'ikram', 'ikrar', 'ilham', 'ilian', 'ilusi', 'imaji', 'imani',
            'imbal', 'imbas', 'imbuh', 'iming', 'impak', 'impas', 'impit',
            'inang', 'incar', 'incit', 'incut', 'indah', 'indik', 'indra',
            'induk', 'infak', 'ingat', 'ingin', 'ingus', 'injak', 'injap',
            'insaf', 'insan', 'inset', 'intan', 'intim', 'iodin', 'irama',
            'isbat', 'iseng', 'isian', 'istal', 'istri', 'iuran', 'jabal',
            'jabar', 'jabir', 'jadah', 'jaduk', 'jagal', 'jagat', 'jahat',
            'jahil', 'jahit', 'jajak', 'jajan', 'jajar', 'jaksa', 'jakun',
            'jalal', 'jalan', 'jalar', 'jalin', 'jalur', 'jamah', 'jamak',
            'jamal', 'jambe', 'jambu', 'jampi', 'jamur', 'janda', 'janin',
            'janji', 'jarak', 'jaran', 'jarum', 'jasad', 'jatah', 'jatuh',
            'jawab', 'jawat', 'jebah', 'jebur', 'jegil', 'jejal', 'jejas',
            'jejer', 'jelak', 'jenis', 'jenuh', 'jepit', 'jeram', 'jerat',
            'jerit', 'jeruk', 'jewer', 'jihat', 'jijik', 'jilat', 'jilid',
            'jimat', 'jinak', 'jiran', 'jirat', 'jirus', 'jisim', 'jitok',
            'jodoh', 'joget', 'johar', 'jompo', 'juang', 'juara', 'judes',
            'judul', 'juita', 'jujur', 'jukut', 'julai', 'jumpa', 'jumud',
            'jurai', 'kabar', 'kabel', 'kabil', 'kabin', 'kabir', 'kabul',
            'kabur', 'kabut', 'kacak', 'kacam', 'kacau', 'kacir', 'kacuk',
            'kadal', 'kadam', 'kadar', 'kadas', 'kader', 'kadet', 'kadim',
            'kafir', 'kagak', 'kaget', 'kagok', 'kagum', 'kahar', 'kahwa',
            'kakah', 'kakak', 'kakap', 'kakas', 'kakek', 'kakus', 'kalah',
            'kalam', 'kalap', 'kalar', 'kalas', 'kalau', 'kalbu', 'kalem',
            'kalis', 'kalui', 'kalut', 'kamar', 'kamil', 'kamit', 'kamus',
            'kanak', 'kanal', 'kanan', 'kanji', 'kanon', 'kanta', 'kanti',
            'kanya', 'kapah', 'kapak', 'kapal', 'kapan', 'kapas', 'kapit',
            'kapok', 'kapri', 'kapuk', 'kapur', 'karam', 'karas', 'karau',
            'karet', 'kargo', 'karib', 'karih', 'karim', 'karsa', 'karya',
            'kasah', 'kasam', 'kasap', 'kasar', 'kasep', 'kasih', 'kasim',
            'kasip', 'kasir', 'kasta', 'kasur', 'kasus', 'katai', 'katak',
            'katek', 'kates', 'katib', 'katik', 'katil', 'katir', 'katup',
            'kausa', 'kawah', 'kawal', 'kawan', 'kawat', 'kawin', 'kayuh',
            'kebal', 'kebat', 'kebun', 'kebut', 'kecap', 'kecil', 'kecoh',
            'kecut', 'kedai', 'kedap', 'kedau', 'keder', 'kedip', 'kedok',
            'keduk', 'kejai', 'kejam', 'kejap', 'kejar', 'kejen', 'kejut',
            'kekah', 'kekal', 'kekar', 'keker', 'kelam', 'kelar', 'kelas',
            'kelek', 'kelih', 'kelik', 'kelim', 'kelip', 'kelok', 'kelor',
            'kelua', 'keluh', 'keluk', 'kemah', 'kemas', 'kemih', 'kemik',
            'kempa', 'kenal', 'kendi', 'kenes', 'kenop', 'kenya', 'kepak',
            'kepal', 'kepek', 'kepet', 'kepil', 'kepis', 'kepot', 'kepuk',
            'kerah', 'kerai', 'kerak', 'keran', 'kerap', 'keras', 'kerat',
            'kerau', 'kerek', 'keren', 'kerih', 'kerik', 'kerja', 'keroh',
            'kerok', 'keruh', 'kerut', 'kesah', 'kesal', 'kesan', 'kesat',
            'keset', 'ketai', 'ketak', 'ketam', 'ketan', 'ketap', 'ketat',
            'ketel', 'ketip', 'ketua', 'ketuk', 'ketul', 'ketur', 'ketus',
            'khali', 'kiara', 'kibas', 'kibul', 'kibut', 'kicau', 'kidal',
            'kidul', 'kikih', 'kikir', 'kikis', 'kikuk', 'kilah', 'kilai',
            'kilap', 'kilar', 'kilas', 'kilat', 'kilau', 'kilik', 'kilir',
            'kimia', 'kinja', 'kipas', 'kirab', 'kirai', 'kirau', 'kirik',
            'kisah', 'kisar', 'kisik', 'kisut', 'kitab', 'klaim', 'klien',
            'klise', 'kobah', 'kobar', 'kober', 'kobra', 'kocak', 'kocek',
            'kocok', 'kodak', 'kodok', 'kojoh', 'kolam', 'kolek', 'kolom',
            'kolot', 'komet', 'konco', 'konde', 'konon', 'kopek', 'koran',
            'korek', 'koroh', 'korps', 'korup', 'kosen', 'kotak', 'kotes',
            'kotok', 'kotor', 'koyak', 'krama', 'kredo', 'krida', 'kroco',
            'kromo', 'kroni', 'kuala', 'kuali', 'kuasa', 'kuasi', 'kubak',
            'kubin', 'kubis', 'kubra', 'kubur', 'kubus', 'kucam', 'kucir',
            'kucup', 'kucur', 'kudai', 'kudap', 'kudis', 'kuduk', 'kudus',
            'kufur', 'kujur', 'kujut', 'kukuh', 'kukur', 'kukus', 'kulai',
            'kulat', 'kulir', 'kulit', 'kulup', 'kumal', 'kuman', 'kumat',
            'kumba', 'kumbu', 'kumis', 'kumuh', 'kunci', 'kuota', 'kupon',
            'kurap', 'kurik', 'kurir', 'kurma', 'kursi', 'kurun', 'kurus',
            'kusam', 'kusir', 'kusta', 'kusuk', 'kusut', 'kutil', 'kutip',
            'kutub', 'kutuk', 'kuyup', 'label', 'labil', 'labuh', 'lacur',
            'ladam', 'ladan', 'lafal', 'lagak', 'lagam', 'lahan', 'lahap',
            'lahar', 'lahat', 'lahir', 'lajak', 'lajat', 'lajur', 'lakon',
            'lalai', 'lalap', 'lalat', 'lamat', 'lampu', 'lamun', 'lamur',
            'lanun', 'lapak', 'lapik', 'lapis', 'lapuk', 'laras', 'larat',
            'larik', 'laris', 'larut', 'larva', 'latah', 'latar', 'laten',
            'laung', 'lawak', 'lawan', 'lawas', 'layak', 'layar', 'layon',
            'layuh', 'lazim', 'lebah', 'lebar', 'lebat', 'lebih', 'lebur',
            'leceh', 'lecek', 'lecet', 'lecut', 'ledak', 'ledek', 'legal',
            'legit', 'leher', 'lekas', 'lekat', 'lekuk', 'lekum', 'lelah',
            'lelap', 'leleh', 'leler', 'lelet', 'lemah', 'lemak', 'lemas',
            'lembu', 'lemon', 'lensa', 'lepas', 'lepra', 'lepuh', 'lerai',
            'leret', 'lesap', 'lesus', 'letak', 'letih', 'level', 'lever',
            'lewah', 'lewat', 'leyeh', 'lezat', 'liang', 'libat', 'libra',
            'libur', 'licik', 'licin', 'lidah', 'lihai', 'lihat', 'lilin',
            'lilit', 'limas', 'limau', 'limit', 'limpa', 'lindu', 'lipan',
            'lipas', 'lipat', 'lipit', 'lipur', 'lirih', 'lirik', 'lisan',
            'lisut', 'logam', 'logat', 'logis', 'lokal', 'lolos', 'lomba',
            'lonte', 'loper', 'lorek', 'lotre', 'lotus', 'loyal', 'luang',
            'luber', 'lubuk', 'lucah', 'lucut', 'ludah', 'ludes', 'lugas',
            'luhur', 'luluh', 'lulur', 'lulus', 'lumat', 'lumba', 'lumer',
            'lumut', 'lunak', 'lunas', 'lunta', 'luput', 'lurah', 'luruh',
            'lurus', 'lusin', 'lusuh', 'lutut', 'luwes', 'mabuk', 'macak',
            'macam', 'macan', 'macet', 'macis', 'madah', 'madat', 'madya',
            'magma', 'mahal', 'mahar', 'mahdi', 'mahir', 'majal', 'majas',
            'majir', 'makam', 'makan', 'makar', 'makin', 'makna', 'makro',
            'makul', 'malah', 'malai', 'malam', 'malap', 'malar', 'malas',
            'malih', 'malik', 'malim', 'malis', 'malit', 'mamak', 'maman',
            'mambo', 'mampu', 'manah', 'manai', 'mandi', 'mandu', 'mangu',
            'mania', 'manik', 'manir', 'manis', 'manja', 'mapak', 'mapan',
            'marah', 'marak', 'marem', 'marga', 'marit', 'marus', 'marut',
            'masak', 'masam', 'masif', 'masih', 'masin', 'masir', 'massa',
            'masuk', 'matai', 'matra', 'matur', 'matut', 'maung', 'mawar',
            'mawas', 'mayat', 'mayor', 'mebel', 'medan', 'media', 'medio',
            'medit', 'medok', 'megah', 'megap', 'megar', 'megat', 'megol',
            'mejam', 'mekar', 'mekik', 'melar', 'melek', 'meler', 'melet',
            'melit', 'melut', 'memar', 'menak', 'mengi', 'menir', 'menur',
            'mepet', 'merah', 'mercu', 'merdu', 'merek', 'merem', 'merih',
            'merot', 'merta', 'merut', 'mesem', 'mesin', 'mesiu', 'meski',
            'mesra', 'mesti', 'mesum', 'metal', 'metir', 'mewah', 'miang',
            'midik', 'mileu', 'milik', 'mimpi', 'minat', 'minim', 'minor',
            'minta', 'minum', 'minus', 'mirat', 'mirip', 'miris', 'misai',
            'misal', 'misil', 'mitos', 'mitra', 'mizan', 'mobil', 'modal',
            'model', 'modin', 'modis', 'mogok', 'mohon', 'molar', 'molek',
            'molor', 'momen', 'momok', 'moral', 'motel', 'motif', 'motor',
            'muara', 'mudah', 'mudik', 'mudin', 'mujur', 'mukah', 'mukim',
            'mukul', 'mukun', 'mulai', 'mulas', 'mulia', 'muluk', 'mulus',
            'mulut', 'mumuk', 'munci', 'mundi', 'mungu', 'munib', 'murad',
            'murah', 'muram', 'murba', 'murid', 'murka', 'murni', 'murup',
            'murus', 'musik', 'musim', 'musuh', 'nadam', 'nadir', 'nafas',
            'nafsi', 'nafsu', 'nagak', 'nahan', 'nahas', 'najis', 'nakal',
            'nalar', 'namun', 'nanah', 'nanai', 'nanap', 'nanar', 'nanti',
            'napal', 'napan', 'napas', 'napuh', 'nasab', 'nasal', 'nasar',
            'nasib', 'natur', 'nayam', 'nazar', 'nekat', 'nenek', 'nenen',
            'nenes', 'netra', 'ngais', 'ngilu', 'ngira', 'nifak', 'nikah',
            'nilai', 'nilam', 'nilik', 'nilon', 'nirai', 'nisan', 'nisbi',
            'nobat', 'nocat', 'nomad', 'nomor', 'norak', 'norma', 'notak',
            'notes', 'novel', 'nujum', 'nunda', 'nusuk', 'nyala', 'nyali',
            'nyata', 'nyawa', 'nyeri', 'nyiru', 'nyiur', 'oasis', 'obeng',
            'objek', 'obral', 'obrol', 'oknum', 'oleng', 'oliva', 'ombak',
            'omong', 'oncor', 'onyok', 'onyot', 'opini', 'opium', 'oplah',
            'oplos', 'optis', 'orang', 'orasi', 'orbit', 'order', 'organ',
            'orong', 'osean', 'oyong', 'pacak', 'pacar', 'pacet', 'pacok',
            'pacul', 'padam', 'padan', 'padas', 'padat', 'padma', 'padmi',
            'padri', 'pagan', 'pagar', 'pagon', 'pagut', 'paham', 'pahat',
            'pahit', 'pajak', 'pajuh', 'pakai', 'pakan', 'pakar', 'pakde',
            'pakem', 'paket', 'pakis', 'paksa', 'paksi', 'pakta', 'pakus',
            'palai', 'palak', 'palam', 'palar', 'palas', 'paldu', 'palit',
            'palka', 'palsu', 'palun', 'palut', 'paman', 'pamer', 'pamit',
            'pamor', 'panah', 'panai', 'panas', 'panca', 'panci', 'pandu',
            'panen', 'panik', 'panji', 'panti', 'papah', 'papak', 'papan',
            'papar', 'paraf', 'parah', 'parak', 'paran', 'paras', 'parau',
            'parih', 'parit', 'paruh', 'parut', 'pasah', 'pasai', 'pasak',
            'pasal', 'pasar', 'paser', 'pasif', 'pasir', 'pasok', 'pasta',
            'pasti', 'pasuk', 'patah', 'patar', 'patek', 'paten', 'pater',
            'patih', 'patik', 'patil', 'patok', 'patos', 'patri', 'patuh',
            'patuk', 'patut', 'pause', 'pawai', 'payah', 'payau', 'pecah',
            'pecak', 'pecut', 'pedal', 'pedar', 'pedas', 'pedet', 'pedih',
            'pegal', 'pegan', 'pegas', 'pegat', 'pegun', 'pejal', 'pejam',
            'pekak', 'pekan', 'pekat', 'pekau', 'pekik', 'pekuk', 'pelak',
            'pelan', 'pelat', 'pelet', 'pelik', 'pelir', 'pelit', 'peloh',
            'pelor', 'peluh', 'peluk', 'pemeo', 'penat', 'penis', 'penuh',
            'penyu', 'pepah', 'pepas', 'pepat', 'pepes', 'pepet', 'perah',
            'perai', 'perak', 'peram', 'peran', 'perca', 'perdu', 'peres',
            'pergi', 'peria', 'perih', 'perlu', 'peron', 'perot', 'perut',
            'pesai', 'pesam', 'pesan', 'pesat', 'pesek', 'pesta', 'petai',
            'petak', 'petir', 'petua', 'petus', 'petut', 'peyot', 'piala',
            'piama', 'piano', 'piara', 'picik', 'picis', 'pihak', 'pijah',
            'pijak', 'pijar', 'pijat', 'piket', 'pikir', 'pikul', 'pikun',
            'pilah', 'pilar', 'pilek', 'pilih', 'pilin', 'pilon', 'pilot',
            'pinar', 'pinda', 'pintu', 'pinus', 'pipet', 'pipih', 'pipis',
            'pipit', 'pirai', 'pirau', 'pirsa', 'pisah', 'pisau', 'pises',
            'pitam', 'piton', 'pivot', 'plang', 'plato', 'pleno', 'plong',
            'pohon', 'pojok', 'poket', 'pokok', 'polah', 'poles', 'polos',
            'pompa', 'popok', 'porak', 'porno', 'poros', 'porsi', 'potek',
            'potol', 'prabu', 'praja', 'premi', 'prima', 'prosa', 'psike',
            'puaka', 'puasa', 'puber', 'pucat', 'pucuk', 'pudar', 'puder',
            'pugak', 'pugar', 'puguh', 'puing', 'puisi', 'pukal', 'pukat',
            'pukau', 'pukul', 'pulas', 'pulau', 'pulih', 'pulsa', 'puluh',
            'pulun', 'pulut', 'punah', 'punca', 'pundi', 'punuk', 'punya',
            'pupil', 'pupuh', 'pupuk', 'pupur', 'pupus', 'puput', 'purba',
            'purna', 'puruk', 'purwa', 'pusam', 'pusar', 'pusat', 'puspa',
            'pusut', 'putar', 'puter', 'putih', 'putik', 'putra', 'putri',
            'putus', 'puyuh', 'qadar', 'qadim', 'qalam', 'qanun', 'qasar',
            'quran', 'rabak', 'rabat', 'rabik', 'rabit', 'rabuk', 'rabun',
            'racun', 'radai', 'radar', 'radas', 'radis', 'ragam', 'ragil',
            'ragut', 'rahak', 'rahib', 'rahim', 'rajah', 'rajin', 'rajut',
            'rakit', 'raksa', 'rakus', 'ralat', 'ramah', 'ramai', 'ramal',
            'rambu', 'ramin', 'ranah', 'rancu', 'randa', 'randu', 'rapal',
            'rapat', 'rapik', 'rapuh', 'rapun', 'rasam', 'rasio', 'ratna',
            'ratus', 'rawan', 'rawat', 'rawit', 'rayap', 'rebah', 'rebeh',
            'rebes', 'rebon', 'rebut', 'recok', 'redam', 'redum', 'redup',
            'rehat', 'rekan', 'relai', 'reluk', 'remah', 'remai', 'remas',
            'remuk', 'renda', 'renik', 'rente', 'repas', 'repot', 'reput',
            'reras', 'resah', 'resam', 'resek', 'resep', 'resmi', 'restu',
            'retak', 'retas', 'retur', 'rewel', 'rezim', 'riang', 'ribut',
            'ricuh', 'ridip', 'rikuh', 'rimba', 'rinai', 'rindu', 'risau',
            'riset', 'ritme', 'rival', 'robek', 'roboh', 'robok', 'robot',
            'roket', 'rokok', 'roman', 'rompi', 'ronda', 'ronta', 'rosot',
            'royal', 'ruang', 'ruaya', 'rudal', 'rudin', 'rujuk', 'rukun',
            'rumah', 'rumit', 'rungu', 'runut', 'rusak', 'rusuh', 'rusuk',
            'ruwah', 'ruwat', 'ruwet', 'ruyup', 'saban', 'sabar', 'sabda',
            'sabet', 'sabit', 'sabot', 'sabuk', 'sabun', 'sabur', 'sabut',
            'sadak', 'sadap', 'sadar', 'sadau', 'sadel', 'sadik', 'sadis',
            'sadur', 'sagur', 'saham', 'sahih', 'sahut', 'saing', 'sains',
            'sajak', 'sakal', 'sakar', 'sakat', 'sakit', 'saksi', 'sakti',
            'salah', 'salai', 'salak', 'salam', 'salat', 'saldo', 'saleh',
            'salib', 'salih', 'salim', 'salin', 'salip', 'saluk', 'salur',
            'salut', 'samak', 'saman', 'samar', 'sampo', 'samun', 'sanak',
            'sanda', 'sandi', 'sanga', 'sangu', 'sapau', 'sapit', 'sapta',
            'saput', 'saraf', 'sarak', 'saran', 'sarap', 'sarit', 'sasap',
            'sasar', 'satir', 'satwa', 'saung', 'sawah', 'sawan', 'sawar',
            'sawer', 'sayap', 'sayat', 'sayup', 'sayur', 'sebab', 'sebal',
            'sebam', 'sebar', 'sebat', 'sebit', 'sebun', 'sebut', 'sedan',
            'sedap', 'sedat', 'sedia', 'sedih', 'sedot', 'seduh', 'segan',
            'segar', 'segeh', 'segel', 'sehat', 'seisi', 'sejak', 'sejuk',
            'sekam', 'sekap', 'sekar', 'sekat', 'sekon', 'sekop', 'seksi',
            'sekte', 'selak', 'selam', 'selap', 'selat', 'selia', 'selip',
            'selir', 'selit', 'selop', 'seluk', 'semai', 'semak', 'semat',
            'semau', 'semen', 'semir', 'semua', 'semut', 'senak', 'senam',
            'senat', 'senda', 'sendi', 'sendu', 'senja', 'sepah', 'sepak',
            'sepat', 'sepoi', 'sepuh', 'sepur', 'serah', 'serak', 'seram',
            'serap', 'serat', 'serba', 'serbu', 'serep', 'seret', 'serok',
            'serta', 'sertu', 'serut', 'sesak', 'sesal', 'sesap', 'sesat',
            'setan', 'setel', 'setem', 'setia', 'setik', 'setip', 'setir',
            'setor', 'sewot', 'siaga', 'siang', 'siapa', 'sibak', 'sibar',
            'sibuk', 'sidik', 'sifar', 'sifat', 'sigap', 'sigar', 'sihir',
            'sikap', 'sikat', 'siksa', 'sikut', 'silam', 'silap', 'silat',
            'silau', 'silih', 'silir', 'simak', 'sinar', 'singa', 'sinis',
            'sinse', 'sinus', 'sipil', 'sipir', 'siput', 'sirah', 'siram',
            'siran', 'sirap', 'sirep', 'sirih', 'sirik', 'sirip', 'sirna',
            'sirop', 'sisih', 'sisir', 'siswa', 'sitir', 'situs', 'skala',
            'skema', 'skors', 'skrip', 'skuat', 'slang', 'sobat', 'sobek',
            'sodok', 'sodor', 'sogok', 'sohib', 'sohor', 'solar', 'solid',
            'sopan', 'sopir', 'sorai', 'sorak', 'sorot', 'sosok', 'sosor',
            'spion', 'spons', 'sport', 'start', 'stepa', 'strap', 'stres',
            'strip', 'studi', 'suaka', 'suami', 'suara', 'suatu', 'subuh',
            'subur', 'sudah', 'sudut', 'sugih', 'suguh', 'sujud', 'sukar',
            'sukat', 'sukma', 'sulam', 'sulap', 'sulih', 'sulit', 'suluh',
            'suluk', 'sulut', 'sumbu', 'sumur', 'sunah', 'sunat', 'sungu',
            'sunyi', 'supel', 'super', 'surai', 'suram', 'surat', 'surau',
            'surga', 'surih', 'suruh', 'suruk', 'surup', 'surut', 'surya',
            'susah', 'susuh', 'susuk', 'susul', 'susun', 'susup', 'susur',
            'susut', 'suwir', 'syair', 'syiar', 'syiwa', 'syura', 'tabah',
            'tabel', 'tabib', 'tabik', 'tabir', 'tabok', 'tabuh', 'tabur',
            'tadah', 'tadir', 'tagak', 'tagan', 'tagar', 'tagih', 'tagut',
            'tahak', 'tahan', 'tahap', 'tahir', 'tahun', 'taiko', 'tajak',
            'tajam', 'tajin', 'tajuk', 'takal', 'takar', 'takat', 'takik',
            'takir', 'taksa', 'takuk', 'takut', 'takwa', 'talah', 'talak',
            'talam', 'talas', 'tamah', 'tamak', 'tamam', 'taman', 'tamat',
            'tanah', 'tanak', 'tanam', 'tanau', 'tanda', 'tandu', 'tanpa',
            'tante', 'tanur', 'tanya', 'tapak', 'tapal', 'tapir', 'tapis',
            'tapuk', 'tapus', 'taraf', 'tarak', 'tarif', 'tarik', 'taris',
            'taruh', 'taruk', 'tarup', 'tasik', 'tatah', 'tatal', 'tatap',
            'tatar', 'tauke', 'tawan', 'tawar', 'tawon', 'tebah', 'tebak',
            'tebal', 'tebas', 'tebat', 'tebok', 'tebuk', 'tebus', 'tedas',
            'teduh', 'tegah', 'tegak', 'tegap', 'tegar', 'tegas', 'tegel',
            'teguh', 'teguk', 'tegun', 'tegur', 'tekad', 'tekak', 'tekan',
            'tekek', 'tekel', 'teken', 'tekor', 'tekun', 'telah', 'telak',
            'telan', 'telas', 'telat', 'teler', 'telik', 'telor', 'teluh',
            'telur', 'telus', 'telut', 'teman', 'tempo', 'tenar', 'tenat',
            'tenda', 'tenok', 'tensi', 'tentu', 'tenun', 'teori', 'tepak',
            'tepas', 'tepat', 'tepik', 'tepis', 'tepok', 'tepos', 'tepuk',
            'terak', 'teral', 'teran', 'terap', 'teras', 'terik', 'terka',
            'teror', 'terpa', 'teruk', 'terup', 'terus', 'tesis', 'tetak',
            'tetap', 'tetar', 'tetas', 'tetek', 'tetes', 'tetua', 'tewas',
            'tiada', 'tiang', 'tiban', 'tidak', 'tidur', 'tikai', 'tikam',
            'tikar', 'tikas', 'tiket', 'tilap', 'timba', 'timpa', 'tinja',
            'tinju', 'tinta', 'tipar', 'tipis', 'tirai', 'tiran', 'tiras',
            'tiris', 'tirus', 'tisik', 'titah', 'titan', 'titel', 'titik',
            'titip', 'titir', 'titis', 'tobak', 'tobat', 'toboh', 'tohok',
            'tohor', 'tokak', 'tokek', 'tokoh', 'tokok', 'tolak', 'tolan',
            'toleh', 'tolok', 'tolol', 'tonil', 'topan', 'topek', 'topik',
            'toreh', 'torso', 'total', 'totok', 'totol', 'toyor', 'trans',
            'trofi', 'tuala', 'tuang', 'tubir', 'tubuh', 'tuduh', 'tugas',
            'tujah', 'tukar', 'tukas', 'tukik', 'tukul', 'tulah', 'tulen',
            'tulis', 'tulus', 'tuman', 'tumor', 'tumpu', 'tumus', 'tunai',
            'tunak', 'tunas', 'tunda', 'tupai', 'turun', 'turus', 'turut',
            'tusuk', 'tutor', 'tutul', 'tutup', 'tutur', 'udang', 'udara',
            'udeng', 'ujana', 'ujang', 'ujian', 'ujung', 'ulama', 'ulang',
            'ultra', 'ulung', 'umbai', 'umbuk', 'umbul', 'umpak', 'umpan',
            'umpat', 'umpet', 'umpuk', 'undak', 'unduk', 'undur', 'ungap',
            'union', 'unjuk', 'unsur', 'untai', 'untal', 'untuk', 'untut',
            'upaya', 'upeti', 'urine', 'urung', 'usaha', 'usang', 'uskup',
            'ustaz', 'utama', 'utang', 'utara', 'uvula', 'vakum', 'valid',
            'venom', 'venus', 'verba', 'versi', 'vespa', 'veter', 'video',
            'virgo', 'vista', 'vital', 'vokal', 'vonis', 'wabah', 'wadah',
            'wadak', 'wadam', 'waduh', 'waduk', 'wagon', 'wahah', 'wahai',
            'wahid', 'wahyu', 'wajah', 'wajan', 'wajar', 'wajib', 'wakaf',
            'wakil', 'waktu', 'walau', 'wangi', 'wanti', 'waras', 'warga',
            'waris', 'warna', 'warni', 'warok', 'warsa', 'warta', 'wasir',
            'wasit', 'watak', 'watan', 'watas', 'wijen', 'wilis', 'wisma',
            'wreda', 'wujud', 'xilan', 'xilem', 'yaitu', 'yakin', 'yakni',
            'yuris', 'zabib', 'zakat', 'zalim', 'zaman', 'zamin', 'zarah',
            'zebra', 'zenit', 'zikir', 'zirah', 'zuhur']
        self.punctset = ["!", "@", "#", "$", "%", "^", "&", "*", "(", ")"]
        self.numset = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]

    def generate(self):
        value = md5(self.uri + self.user + self.secret + GARBAGE).hexdigest()
        hash = []
        num = 0
        for i in range(len(value)/4):
            hash.append(value[num:num+4])
            num += 4
        words = []
        for x in [hash[0], hash[2], hash[4], hash[6]]:
            words.append(self.wordset[(sum([ord(i) for i in x]) * 408) % 2742])
        puncts = []
        for y in [hash[1], hash[3], hash[5], hash[7]]:
            puncts.append(self.punctset[(sum([ord(i) for i in y]) * 408) % 10])
        numbers = []
        for z in [hash[1], hash[3], hash[5], hash[7]]:
            numbers.append(self.numset[(sum([ord(i) for i in z]) * 408) % 10])
        return "%s%s%s%s%s%s%s%s%s%s%s%s" % (words[0], words[1].upper(),
            puncts[0], puncts[1], words[2], words[3].title(), numbers[0],
            numbers[1], numbers[2], numbers[3], puncts[2], puncts[3])


def pbcopy(data):
    # OSX only.. calling pbcopy(1), provide copying to the Clipboard
    # http://www.devx.com/opensource/Article/37233/0/page/3
    p = subprocess.Popen(['pbcopy'], stdin=subprocess.PIPE)
    p.stdin.write(data)
    p.stdin.close()
    retcode = p.wait()
    return retcode


def main():
    uri = raw_input("URI: ")
    user = raw_input("User: ")
    secret = getpass("Master password: ")
    password = _GiveMeAKey(uri, user, secret).generate()
    #print "Password:", password
    pbcopy(password)


if __name__ == "__main__":
    main()
